### ISSUE TITLE
String.prototype.endsWith

### ISSUE THREAD

**Issue by gleidsonh** [gleidsonh/painless-code#3]
Create String.prototype.endsWith, with 3 parameters: "string to check", "position" (optional)

```js
'Test'.endsWith('t')     // true
'Test'.endsWith('st')    // true
'Test'.endsWith('s', 2)  // true
'Test'.endsWith('es', 2) // true
'Test'.endsWith('a')     // false
'Test'.endsWith('T')     // false (case sensitive)
```

**Comment by solrachix** [comment]
I believe that this function was implemented in ES6 
[String.prototype.endsWith MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith)
